import {
  mdiAccount,
  mdiAccountGroup,
  mdiBriefcase,
  mdiCashMultiple,
  mdiChartPie,
  mdiCheck,
  mdiChevronDown,
  mdiChevronUp,
  mdiClose,
  mdiCog,
  mdiContentCopy,
  mdiContentSave,
  mdiDatabase,
  mdiDeleteOutline,
  mdiDownload,
  mdiEye,
  mdiFileDocumentOutline,
  mdiHammerWrench,
  mdiHome,
  mdiLogout,
  mdiMenu,
  mdiNoteOutline,
  mdiPackageVariant,
  mdiPencil,
  mdiPlus,
  mdiPrinter,
  mdiRefresh,
  mdiViewDashboard,
} from '@mdi/js';

/** Noms alignés sur MaterialCommunityIcons (app mobile). */
export const ADMIN_ICONS = {
  home: mdiHome,
  'view-dashboard': mdiViewDashboard,
  briefcase: mdiBriefcase,
  'account-group': mdiAccountGroup,
  'hammer-wrench': mdiHammerWrench,
  'package-variant': mdiPackageVariant,
  cog: mdiCog,
  account: mdiAccount,
  logout: mdiLogout,
  menu: mdiMenu,
  database: mdiDatabase,
  'chart-pie': mdiChartPie,
  'file-document': mdiFileDocumentOutline,
  'cash-multiple': mdiCashMultiple,
  printer: mdiPrinter,
  download: mdiDownload,
  eye: mdiEye,
  pencil: mdiPencil,
  plus: mdiPlus,
  check: mdiCheck,
  close: mdiClose,
  'content-save': mdiContentSave,
  'content-copy': mdiContentCopy,
  delete: mdiDeleteOutline,
  refresh: mdiRefresh,
  'note-outline': mdiNoteOutline,
  'chevron-up': mdiChevronUp,
  'chevron-down': mdiChevronDown,
};

export function getAdminIconPath(name) {
  return ADMIN_ICONS[name] || null;
}
